### ISSUE TITLE
spark: integration with timelineserver 

### ISSUE THREAD

**Issue by mehdibn** [TOSIT-IO/tdp-collection#143]
When `spark.hadoop.yarn.timeline-service.enabled` is enabled in `spark-default.conf` and you do a `spark-submit`, this error id generated:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jersey/api/client/config/ClientConfig. It appears that the timeline client failed to initiate because an incompatible dependency in classpath. If timeline service is optional to this client, try to work around by setting yarn.timeline-service.enabled to false in client configuration.
	at org.apache.hadoop.yarn.client.api.impl.TimelineClientImpl.createTimelineConnector(TimelineClientImpl.java:135)
	at org.apache.hadoop.yarn.client.api.impl.TimelineClientImpl.serviceInit(TimelineClientImpl.java:118)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.getTimelineDelegationToken(YarnClientImpl.java:387)
	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.addTimelineDelegationToken(YarnClientImpl.java:363)
	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.submitApplication(YarnClientImpl.java:282)
	at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:175)
	at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:57)
	at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:164)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:500)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2493)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:934)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:925)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:925)
	at org.apache.spark.examples.JavaSparkPi.main(JavaSparkPi.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:890)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:192)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:217)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

**Comment by rpignolet** [comment]
Resolved

**Comment by ChristopheLRTE** [comment]
Hello @rpignolet.

We're facing a similar issue.

So I was wondering how you solved this one please (_I didn't find the involved commit_) ?

Thank you for your help.
C.L.

**Comment by mehdibn** [comment]
Hello @ChristopheLRTE 

`spark.hadoop.yarn.timeline-service.enabled` must be `false` as you can see in the [spark configuration](https://github.com/TOSIT-IO/tdp-collection/blob/ba280c1c3cd63d3ee27d9e24e5653a44f372d09a/tdp_vars_defaults/spark/spark.yml#L83)

and thanks to this [PR](https://github.com/TOSIT-IO/tdp-collection/pull/142), Timeline HA issue is resolved now,

PS: with this configuration, you can find all your jobs in the timeline server, even `spark.hadoop.yarn.timeline-service.enabled=false`

**Comment by ChristopheLRTE** [comment]
Hello @mehdibn,

Thank you for your feedback.

Indeed, I had not specified our context in relation to the case you encountered.

Concerning our issue, the `hadoop-yarn-timelineserver.service` service was active. We encountered almost the same error and got around it by changing the `yarn.timeline-service.enabled` parameter to `false` for the Edge's `yarn-site.xml` file. That's what the error message advised :

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jersey/api/client/config/ClientConfig.
It appears that the timeline client failed to initiate because an incompatible dependency in classpath.
If timeline service is optional to this client, try to work around by setting yarn.timeline-service.enabled to false in client configuration.
at org.apache.hadoop.yarn.client.api.impl.TimelineClientImpl.createTimelineConnector(TimelineClientImpl.java:135) 
```

Another possible workaround was to add a `.setConf("spark.hadoop.yarn.timeline-service.enabled", "false")` parameter to the `sparkLauncher` that runs the Spark 2 job (_this may be similar to the previous point ?_).

Finally, another method worked, adding the jar `jersey-bundle-1.17.jar` in the dependencies folder (_e.g. `/opt/tdp/spark-2.3.5-TDP-0.1.0-SNAPSHOT-bin-tdp/jars`_) and leaving the `yarn.timeline-service.enabled` parameter to `true`. Thus, the processing no longer fell into error.

I don't know if this is something you encountered too. And, what do you think about it ?

Thank you in advance.
