### ISSUE TITLE
Spark 3: Connection to Hive Metastore doesn't work when Hive Server 2 is running on the edge

### ISSUE THREAD

**Issue by Nuttymoon** [TOSIT-IO/tdp-collection#395]
Similar to #394 but with Spark 3.

The connection to the Hive Metastore from Spark does not work. We can see this by doing a simple `SHOW DATABASES` in `pyspark3` shell:
```py
spark.sql('SHOW DATABASES')
```
With Spark 3, we have the following error:
```
java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
...
Caused by: java.lang.IllegalArgumentException: java.io.IOException: Configuration problem with provider path.
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:459)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:224)
	at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.<init>(SessionHiveMetaStoreClient.java:94)
	... 80 more
Caused by: java.io.IOException: Configuration problem with provider path.
	at org.apache.hadoop.conf.Configuration.getPasswordFromCredentialProviders(Configuration.java:2363)
	at org.apache.hadoop.conf.Configuration.getPassword(Configuration.java:2282)
	at org.apache.hadoop.hive.metastore.conf.MetastoreConf.getPassword(MetastoreConf.java:1537)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:452)
	... 82 more
Caused by: java.io.FileNotFoundException: /etc/hive/conf.s2/hive.jceks (Permission denied)
```
It seems that Spark tries to use Hive CrendentialProvider, but it shouldn't be needed. It is probably a client configuration issue.

**Comment by mehdibn** [comment]
I see the issue .. pyspark command is not well configured via a template.
Please check the [spark-shell template](https://github.com/TOSIT-IO/tdp-collection/blob/master/roles/spark/common/templates/spark-shell-command.j2) for example that is well configured in order to use the specific [hive-site.xml](https://github.com/TOSIT-IO/tdp-collection/blob/master/roles/spark/common/templates/hive-site.xml.j2) that we generated for spark

**Comment by Nuttymoon** [comment]
> I see the issue .. pyspark command is not well configured via a template. Please check the [spark-shell template](https://github.com/TOSIT-IO/tdp-collection/blob/master/roles/spark/common/templates/spark-shell-command.j2) for example that is well configured in order to use the specific [hive-site.xml](https://github.com/TOSIT-IO/tdp-collection/blob/master/roles/spark/common/templates/hive-site.xml.j2) that we generated for spark

`pyspark3` uses the same template as `spark3-shell` and the issue is also present with `spark3-shell`.

**Comment by mehdibn** [comment]
i don't have the same issue in my env : 
```
2022-08-02 15:15:27,504 WARN yarn.Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
Spark context Web UI available at http://mehdi-edge-01.novalocal:4040
Spark context available as 'sc' (master = yarn, app id = application_1659344321529_0024).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.2.2-TDP-0.1.0-SNAPSHOT
      /_/
         
Using Scala version 2.12.15 (OpenJDK 64-Bit Server VM, Java 1.8.0_332)
Type in expressions to have them evaluated.
Type :help for more information.

scala> spark.sql("show databases") ;
Hive Session ID = 09fe89c6-26d5-4341-a910-19bcd2f31c98
res0: org.apache.spark.sql.DataFrame = [namespace: string]

scala> spark.sql("show databases").show() ;
+---------+
|namespace|
+---------+
|  default|
+---------+


scala> 
```

It means that the specifiic hive-site.xml of spark is not loaded ..

**Comment by mehdibn** [comment]
Good News :+1:

**Comment by Nuttymoon** [comment]
Unfortunately, this does not fix the issue when a Hive Server 2 is installed on the edge.
```
Caused by: java.lang.IllegalArgumentException: java.io.IOException: Configuration problem with provider path.
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:459)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.<init>(HiveMetaStoreClient.java:224)
	at org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient.<init>(SessionHiveMetaStoreClient.java:94)
	... 80 more
Caused by: java.io.IOException: Configuration problem with provider path.
	at org.apache.hadoop.conf.Configuration.getPasswordFromCredentialProviders(Configuration.java:2363)
	at org.apache.hadoop.conf.Configuration.getPassword(Configuration.java:2282)
	at org.apache.hadoop.hive.metastore.conf.MetastoreConf.getPassword(MetastoreConf.java:1537)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:452)
	... 82 more
Caused by: java.io.FileNotFoundException: /etc/hive/conf.s2/hive.jceks (Permission denied)
```

**Comment by Nuttymoon** [comment]
I have found a solution anyways. Opening PR in a bit.
