### ISSUE TITLE
yarn resource managers failed to start

### ISSUE THREAD

**Issue by jusstol** [TOSIT-IO/tdp-collection#440]
I work on a cluster where HDFS is already installed externally so there are a lot of HDFS related roles I did not play. That said, I don't know how it could be the cause of my problem which is the following.

When playing playbooks/meta/yarn.yml, Yarn Resource Manager could not start on any of the two nodes :
```
TASK [tosit.tdp.resourcemanager : Start YARN resource managers] ****************************************************************************************************************************************************
fatal: [master-01]: FAILED! => changed=false 
  msg: |-
    Unable to start service hadoop-yarn-resourcemanager: Job for hadoop-yarn-resourcemanager.service failed because the control process exited with error code. See "systemctl status hadoop-yarn-resourcemanager.service" and "journalctl -xe" for details.
fatal: [master-02]: FAILED! => changed=false 
  msg: |-
    Unable to start service hadoop-yarn-resourcemanager: Job for hadoop-yarn-resourcemanager.service failed because the control process exited with error code. See "systemctl status hadoop-yarn-resourcemanager.service" and "journalctl -xe" for details.
```
The reason being (from /var/log/hadoop/yarn/hadoop-yarn-resourcemanager-XXX.log) :
```
2022-09-05 17:20:41,194 FATAL org.apache.hadoop.yarn.server.resourcemanager.ResourceManager: Error starting ResourceManager
org.apache.hadoop.yarn.exceptions.YarnRuntimeException: Invalid configuration! Can not find valid RM_HA_ID. None of yarn.resourcemanager.address.rm1 yarn.resourcemanager.address.rm2  are matching the local address OR yarn.resourcemanager.ha.id is not specified in HA Configuration
        at org.apache.hadoop.yarn.conf.HAUtil.throwBadConfigurationException(HAUtil.java:45)
        at org.apache.hadoop.yarn.conf.HAUtil.verifyAndSetCurrentRMHAId(HAUtil.java:151)
        at org.apache.hadoop.yarn.conf.HAUtil.verifyAndSetConfiguration(HAUtil.java:106)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.serviceInit(ResourceManager.java:270)
        at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
        at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.main(ResourceManager.java:1492)
```
When trying to get service state I encounter the following error :
```
$ yarn rmadmin -getServiceState rm1
Operation failed: Invalid host name: local host is: (unknown); destination host is: "master-01.domain":8033; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost
```
This paragraph from the url printed in the above error got my attention :
> If you are using /etc/hosts files instead of DNS-based lookups and your hosts files have FQDNs, you must ensure that the FQDN includes a **_trailing dot_**. Thus a correct hosts file entry for foo.example.com may look like this.

> `1.2.3.4  foo.example.com foo.example.com. foo`
> The Hadoop host resolver ensures hostnames are terminated with a trailing dot prior to lookup to avoid the security issue described in [RFC 1535](https://ietf.org/rfc/rfc1535.txt).

Then I tried exactly that and it worked. Edited /etc/hosts :
```
# previous version was :
# 10.132.150.217 master-01.domain master-01

10.132.150.217 worker-01.domain worker-01.domain. worker-01
10.132.149.209 worker-02.domain worker-02.domain. worker-02
10.132.149.113 worker-03.domain worker-03.domain. worker-03
10.132.149.110 master-01.domain master-01.domain. master-01
10.132.149.107 master-02.domain master-02.domain. master-02
10.132.149.104 master-03.domain master-03.domain. master-03
10.132.149.103 edge-01.domain edge-01.domain. edge-01
```
Do you have any idea why I encounter this error, and why I would need to edit my hosts file for yarn to resolve rm1 and rm2 addresses ?

**Comment by rpignolet** [comment]
Hi, with the Vagrant deployment it is working for me:

```bash
[yarn@edge-01 ~]$ kinit -kt /etc/security/keytabs/yarn.headless.keytab yarn
[yarn@edge-01 ~]$ yarn rmadmin -getServiceState rm1
standby
[yarn@edge-01 ~]$ yarn rmadmin -getServiceState rm2
active
[yarn@edge-01 ~]$ cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

127.0.0.1 centos7.localdomain


# Ansible inventory hosts BEGIN
192.168.56.13 master-03.tdp master-03
192.168.56.14 worker-01.tdp worker-01
192.168.56.15 worker-02.tdp worker-02
192.168.56.12 master-02.tdp master-02
192.168.56.10 edge-01.tdp edge-01
192.168.56.16 worker-03.tdp worker-03
192.168.56.11 master-01.tdp master-01
# Ansible inventory hosts END
```

Can you reproduce with the Vagrant deployment ?

I will make an issue to add the trailing dot pattern inside `tdp-collection-prerequisites` as stated in Hadoop documentation.

**Comment by jusstol** [comment]
Thank you for your answer, I will test this out in the following weeks!

**Comment by rpignolet** [comment]
Close as inactive.
