### ISSUE TITLE
Restart of the JournalNodes is dangerous for HDFS stability

### ISSUE THREAD

**Issue by Nuttymoon** [TOSIT-IO/tdp-collection#509]
The operation `hdfs_journalnode_restart` restart all the JournalNodes all at once.

This is quite brutal for the quorum: at OECD, we have experienced several times a de-synchronization of the JournalNodes after a restart, 1 JN being ahead and the 2 other JN refusing to sync as the quorum is not reached. This also keeps the NameNodes from starting as they cannot get a stable state from the JNs.

The following logs reflect the issue:
- On the NameNodes (note that the error is quite misleading as it seems to be related to SSL certs):
  ```
  2022-09-21 09:38:19,044 INFO org.apache.hadoop.hdfs.qjournal.client.QuorumJournalManager: Waited 37002 ms (timeout=120000 ms) for a response for acceptRecovery(startTxId: 971444 endTxId: 971451 isInProgress: true). Succeeded so far: [${JN_IP_1}:8485]. Exceptions so far: [${JN_IP_2}:8485: Error while authenticating with endpoint: https://${JN_IP_2}:8481/getJournal?jid=${clustername}&segmentTxId=971444&storageInfo=-64%3A589208949%3A1658405790856%3ACID-1122f02b-79df-4eeb-8cf6-b7f203aac609&inProgressOk=true
          at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
          ...
          at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2678)
  Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
            at sun.security.ssl.Alert.createSSLException(Alert.java:131)
            ...
            at org.apache.hadoop.security.authentication.client.KerberosAuthenticator.authenticate(KerberosAuthenticator.java:189)
            ... 24 more
  Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  ```
- On the 2 de-synced JNs:
  ```
  2022-10-05 11:06:05,396 WARN org.apache.hadoop.hdfs.qjournal.server.Journal: Failed to delete temporary file /mnt/quorum/hdfs/jn/${clustername}/current/edits_inprogress_0000000000000971444.epoch=36

  2022-10-05 11:06:05,397 INFO org.apache.hadoop.ipc.Server: IPC Server handler 1 on 8485, call Call#16 Retry#0 org.apache.hadoop.hdfs.qjournal.protocol.QJournalProtocol.acceptRecovery from ${JN_IP_1}:41237

  javax.net.ssl.SSLHandshakeException: Error while authenticating with endpoint: https://${JN_FQDN_1}:8481/getJournal?jid=${clustername}&segmentTxId=971444&storageInfo=-64%3A589208949%3A1658405790856%3ACID-1122f02b-79df-4eeb-8cf6-b7f203aac609&inProgressOk=true
  ```

The only solution to this issue is to manually replace the edit logs of the 2 de-synced JNs with a copy of the edit logs from the healthy JN. This is pretty dirty.

Did anyone experience the same issue?

I think that we should implement a rolling restart strategy for "quorum" services like JournalNodes and ZooKeeper to avoid corrupting their state.

**Comment by KaidoKopli** [comment]
Could you please update of the status of the rolling update? Tänan!
