### ISSUE TITLE
spark3: spark History Server fails to start

### ISSUE THREAD

**Issue by mehdibn** [TOSIT-IO/tdp-collection#706]
```
2023-02-21 13:26:08,629 - INFO  [main:SslContextFactory@358] - x509=X509@36bc415e(mehdi-master-03.novalocal,h=[mehdi-master-03.novalocal],a=[/172.16.0.153],w=[]) 
for Server@6a714237[provider=null,keyStore=file:///etc/ssl/certs/keystore.jks,trustStore=null]

2023-02-21 13:26:08,640 - ERROR [main:Logging@94] - Failed to bind HistoryServer
java.security.UnrecoverableKeyException: Password must not be null
        at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:134)
        at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:57)
        at sun.security.provider.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:96)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineGetKey(JavaKeyStore.java:71)
        at java.security.KeyStore.getKey(KeyStore.java:1023)
        at sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:145)
        at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:70)
        at javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:256)
        at org.sparkproject.jetty.util.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:1249)
        at org.sparkproject.jetty.util.ssl.SslContextFactory$Server.getKeyManagers(SslContextFactory.java:2364)
        at org.sparkproject.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:373)
        at org.sparkproject.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:244)
        at org.sparkproject.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.sparkproject.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.sparkproject.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.sparkproject.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:97)
        at org.sparkproject.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.sparkproject.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.sparkproject.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.sparkproject.jetty.server.AbstractConnector.doStart(AbstractConnector.java:321)
        at org.sparkproject.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
        at org.sparkproject.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
        at org.sparkproject.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.apache.spark.ui.JettyUtils$.newConnector$1(JettyUtils.scala:303)
        at org.apache.spark.ui.JettyUtils$.sslConnect$1(JettyUtils.scala:322)
        at org.apache.spark.ui.JettyUtils$.$anonfun$startJettyServer$4(JettyUtils.scala:326)
        at org.apache.spark.ui.JettyUtils$.$anonfun$startJettyServer$4$adapted(JettyUtils.scala:326)
        at org.apache.spark.util.Utils$.$anonfun$startServiceOnPort$2(Utils.scala:2383)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
        at org.apache.spark.util.Utils$.startServiceOnPort(Utils.scala:2375)
        at org.apache.spark.ui.JettyUtils$.$anonfun$startJettyServer$2(JettyUtils.scala:326)
        at org.apache.spark.ui.JettyUtils$.$anonfun$startJettyServer$2$adapted(JettyUtils.scala:315)
        at scala.Option.map(Option.scala:230)
        at org.apache.spark.ui.JettyUtils$.startJettyServer(JettyUtils.scala:315)
        at org.apache.spark.ui.WebUI.bind(WebUI.scala:147)
        at org.apache.spark.deploy.history.HistoryServer.bind(HistoryServer.scala:164)
        at org.apache.spark.deploy.history.HistoryServer$.main(HistoryServer.scala:310)
        at org.apache.spark.deploy.history.HistoryServer.main(HistoryServer.scala)
```

**Comment by mehdibn** [comment]
@leopaul36 i think that you can have an idea about this issue ?

**Comment by leopaul36** [comment]
> @leopaul36 i think that you can have an idea about this issue ? is it related to this [feat: move spark hs passwords to a JCEKS file](https://github.com/TOSIT-IO/tdp-collection/commit/3631c0c9fc8a91b42d0f810bf7a99179b2e27dc9) ?

It probably is my bad! Let me run a fresh install and see if I have the same issue

**Comment by leopaul36** [comment]
> > @leopaul36 i think that you can have an idea about this issue ? is it related to this [feat: move spark hs passwords to a JCEKS file](https://github.com/TOSIT-IO/tdp-collection/commit/3631c0c9fc8a91b42d0f810bf7a99179b2e27dc9) ?
> 
> It probably is my bad! Let me run a fresh install and see if I have the same issue

I don't have any issue with a fresh install :confused:
