### ISSUE TITLE
PKIX error : Yarn command

### ISSUE THREAD

**Issue by ChristopheLRTE** [TOSIT-IO/tdp-collection#716]
Hello,

I tried to execute this command line with Yarn `yarn schedulerconf -update "root.prod:capacity=50"` which seems to be a basic one but I get this error message :

`Exception in thread "main" com.sun.jersey.api.client.ClientHandlerException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:155)
        at com.sun.jersey.api.client.Client.handle(Client.java:652)
        at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
        at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
        at com.sun.jersey.api.client.WebResource$Builder.put(WebResource.java:529)
        at org.apache.hadoop.yarn.client.cli.SchedConfCLI.run(SchedConfCLI.java:141)
        at org.apache.hadoop.yarn.client.cli.SchedConfCLI.main(SchedConfCLI.java:69)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:324)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:262)
        at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1356)
        at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1231)
        at sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1174)
        at sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:377)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
        at sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:182)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1397)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1305)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1342)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1317)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
        at com.sun.jersey.client.urlconnection.URLConnectionClientHandler$1$1.getOutputStream(URLConnectionClientHandler.java:238)
        at com.sun.jersey.api.client.CommittingOutputStream.commitStream(CommittingOutputStream.java:117)
        at com.sun.jersey.api.client.CommittingOutputStream.write(CommittingOutputStream.java:89)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at java.io.BufferedWriter.flush(BufferedWriter.java:254)
        at com.sun.jersey.core.util.ReaderWriter.writeToAsString(ReaderWriter.java:191)
        at com.sun.jersey.core.provider.AbstractMessageReaderWriterProvider.writeToAsString(AbstractMessageReaderWriterProvider.java:128)
        at com.sun.jersey.core.impl.provider.entity.StringProvider.writeTo(StringProvider.java:88)
        at com.sun.jersey.core.impl.provider.entity.StringProvider.writeTo(StringProvider.java:58)
        at com.sun.jersey.api.client.RequestWriter.writeRequestEntity(RequestWriter.java:300)
        at com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(URLConnectionClientHandler.java:217)
        at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:153)
        ... 6 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:456)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:323)
        at sun.security.validator.Validator.validate(Validator.java:271)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:315)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:223)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1340)
        ... 37 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:451)
        ... 43 more`

Would you know why please ?

Thank you in advance for your help,
Cheers
C.L.

**Comment by PACordonnier** [comment]
Hi,

This error relates to a TLS error. The Certificate Authority for your organization could not be found in the certificate chain used by the `yarn` command. Java raises an error as the CA of your Yarn RM is not trusted.

You should be able to add your CA to the default java truststore (likely to be `/etc/pki/java/cacerts`) which should fix the issue.

Regards,
PA Cordonnier

**Comment by ChristopheLRTE** [comment]
Hello,

Thank you for your answer !
This point is not yet embedded in the TDP distrib. (I saw some existing certificates stuf included) ?

Cheers

**Comment by PACordonnier** [comment]
It should be embedded but maybe a bug. My guess is that the node running the `yarn` command is only defined as a client (not a Knox Gateway server for example). Is that correct ?

Is SSL-TLS on this node provided by tdp-collection-prerequisite or using your own "tls provider" ?

**Comment by ChristopheLRTE** [comment]
Yes the yarn command is executed within a edge. I added, as you suggested, the CA inside cacerts file and now I obtain a remoteauthentificationexception. 
This concerns the TDP self signed certificate.

**Comment by ChristopheLRTE** [comment]
I think I missclick, the issue seems to be closed but for me it’s not

**Comment by PACordonnier** [comment]
This looks like a Kerberos error to me, but I can't get the same error message if I have no ticket cached (i have no error message besides "Configuration change unsuccessful"). What principal are you using ?

Also be aware that the `schedulerconf` is still in alpha and requires a few changes on your `yarn-site.xml` to work properly. See here https://hadoop.apache.org/docs/stable/hadoop-yarn/hadoop-yarn-site/CapacityScheduler.html#Changing_Queue_Configuration

**Comment by ChristopheLRTE** [comment]
I tried with `yarn` and `hdfs` principals.

Yes, you're right it is in alpha and I tried to access to this URI too : https://IP:PORT/ws/v1/cluster/scheduler-conf 

And here is the result :
![image](https://user-images.githubusercontent.com/95027345/223212008-693433c7-1c90-42af-9262-47d6127d50c3.png)

Moreover, when I launch this `yarn schedulerconf -update "root.prod:capacity=50"`, I get this inside RM Nodes logs :

```
2023-03-06 20:34:02,475 INFO  ipc.Server (Server.java:saslProcess(1845)) - Auth successful for rm/bdpnode01.applispfref.sipfref.local@bdpopf (auth:KERBEROS)
2023-03-06 20:34:02,476 INFO  authorize.ServiceAuthorizationManager (ServiceAuthorizationManager.java:authorize(138)) - Authorization successful for rm/bdpnode01.applispfref.sipfref.local@bdpopf (auth:KERBEROS) for protocol=interface org.apache.hadoop.ha.HAServiceProtocol
```

**Comment by ChristopheLRTE** [comment]
up please :-)

**Comment by PACordonnier** [comment]
I think your last error relates to : https://issues.apache.org/jira/browse/YARN-8559

Basically the GET operation on /scheduler-conf has not been implemented in Hadoop 3.1. (see [this diff](https://github.com/apache/hadoop/commit/d352f167ebb865a6486afbbdac8e2a5e97a7bbad#diff-5ef202cb25766fc8acf9314d5f120f0e9242b10c8fac124747eb8c51c5e17b41)

Regarding the scheduler-conf updates, it works on my environment once I set `yarn.scheduler.configuration.store.class: "memory"`(which is an ephemeral store class but enables the PUT to `/scheduler-conf`)

There are quite a lot of issues JIRA tickets related to this `/scheduler-conf`(both server side and client side) that have not been fixed in Hadoop 3.1 and would require an minor version update on the YARN project.

**Comment by ChristopheLRTE** [comment]
Yeah, you're right, thank you very much !

I was just getting it to work using `zk` mode which seems to be persistent (_to be tested_) unlike `memory` mode.

In summary of my actions to achieve this :
- as you suggested to me solve the SSL problem (_e.g. `ClientHandlerException: javax.net.ssl.SSLHandshakeException: PKIX path building failed ...`_) by : 
   - extracting the `.cer` file from the `trustore.jks` file
   - adding the CA of the Trustore in the `/etc/pki/ca-trust/extracted/java/cacerts` file thanks to this `.cer` file
- reactivate the "kerberos" mode (_which I had voluntarily deactivated, cf. parameter `hadoop.http.authentication.type`, from `simple` to `kerberos`_). I have to confirm now if this is really a blocking point …
- pass the `yarn.scheduler.configuration.store.class parameter` to `memory` or `zk` or `leveldb` to be able to benefit from the REST Api

And, finally I agree with you that there have been changes since version 3.1.1, because I saw some stuff in that way during my researches. But IMHO, I think that upgrading is not so easy :smile:

Thank you again !
Cheers
