### ISSUE TITLE
Running meta/zookeeper.yml twice breaks ZooKeeper (permission denied on /opt/tdp/zookeeper/zkData/version-2/acceptedEpoch.tmp)

### ISSUE THREAD

**Issue by jusstol** [TOSIT-IO/tdp-collection#754]
When we run the zookeeper meta playbook (`tosit.tdp.meta.zookeeper`) twice and then try to restart zookeeper services, they won't manage to elect a leader anymore.

## Error logs
```
2023-05-09 11:53:35,323 - ERROR [LearnerHandler-/10.132.149.110:53690:LearnerHandler@633] - Unexpected exception causing shutdown while sock still open
java.io.FileNotFoundException: /opt/tdp/zookeeper/zkData/version-2/acceptedEpoch.tmp (Permission non accordée)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at org.apache.zookeeper.common.AtomicFileOutputStream.<init>(AtomicFileOutputStream.java:59)
        at org.apache.zookeeper.server.quorum.QuorumPeer.writeLongToFile(QuorumPeer.java:1183)
        at org.apache.zookeeper.server.quorum.QuorumPeer.setAcceptedEpoch(QuorumPeer.java:1229)
        at org.apache.zookeeper.server.quorum.Leader.getEpochToPropose(Leader.java:867)
        at org.apache.zookeeper.server.quorum.LearnerHandler.run(LearnerHandler.java:342)
```

## How to reproduce :
1. run paybook `tosit.tdp.meta.zookeeper`
2. run playbook `tosit.tdp.meta.zookeeper` again
3. run playbook `tosit.tdp.zookeeper_server_restart` to restart the zookeeper system services
4. run `stat` command over each socket :
```bash
echo "stat" | nc node01 2181
# This ZooKeeper instance is not currently serving requests
echo "stat" | nc node02 2181
# This ZooKeeper instance is not currently serving requests
echo "stat" | nc node03 2181
# This ZooKeeper instance is not currently serving requests
```
👉 `zookeeper` system services are up, but not really working.
## How to fix manually

1. run playbook `tosit.tdp.zookeeper_server_stop`
2. on each node running a zookeeper instance, run `chown -R zookeeper:hadoop /opt/tdp/zookeeper/zkData/` command to fix permissions
3. run playbook `tosit.tdp.zookeeper_server_start`
4. test election :
```bash
echo "stat" | nc node01 2181 | grep Mode
# Mode: follower
echo "stat" | nc node02 2181 | grep Mode
# Mode: follower
echo "stat" | nc node03 2181 | grep Mode
# Mode: leader
```
👉 `zookeeper` system services are up, and serving requests.

## Root cause
These are the two playbooks responsible of the change in permissions on the `/opt/tdp/zookeeper/zkData/version-2` folder :
- zookeeper_client_install.yml
- zookeeper_server_install.yml

They both import the `install` tasks from `tosit.tdp.zookeeper.common` which one of the tasks is :
https://github.com/TOSIT-IO/tdp-collection/blob/935d66a8aa17dee851e377aaa147ab829392926f/roles/zookeeper/common/tasks/install.yml#L45-L52
The `recurse: true` sets permissions to `root:root` `775` on all paths underneath /opt/tdp/zookeeper, which breaks ZooKeeper.

**Comment by GuillaumeHold** [comment]
The problem is also present with `tdp deploy`
